---
# Source: ghost/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ghost
  namespace: "ghost"
  labels:
    app.kubernetes.io/name: ghost
    helm.sh/chart: ghost-15.1.0
    app.kubernetes.io/instance: demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: ghost
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ghost
      app.kubernetes.io/instance: demo
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ghost
        helm.sh/chart: ghost-15.1.0
        app.kubernetes.io/instance: demo
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: ghost
      annotations:
        checksum/secrets: 1c200ed34a46df42a3510dcfaf89649b960c3207cb1d37e6d54568c60ffbaaca
    spec:
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: ghost
                    app.kubernetes.io/instance: demo
                namespaces:
                  - "ghost"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
      containers:
        - name: demo-ghost
          image: docker.io/bitnami/ghost:4.22.3-debian-10-r0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "true"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: GHOST_DATABASE_HOST
              value: "demo-mariadb"
            - name: GHOST_DATABASE_PORT_NUMBER
              value: "3306"
            - name: GHOST_DATABASE_NAME
              value: "bitnami_ghost"
            - name: GHOST_DATABASE_USER
              value: "bn_ghost"
            - name: GHOST_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mariadb-password
            - name: GHOST_HOST
              value: "34.89.241.133/"
            - name: GHOST_PORT_NUMBER
              value: "2368"
            - name: GHOST_USERNAME
              value: "user"
            - name: GHOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: ghost-password
            - name: GHOST_EMAIL
              value: "user@example.com"
            - name: GHOST_BLOG_TITLE
              value: "User's Blog"
            - name: GHOST_ENABLE_HTTPS
              value: "no"
            - name: GHOST_EXTERNAL_HTTP_PORT_NUMBER
              value: "80"
            - name: GHOST_EXTERNAL_HTTPS_PORT_NUMBER
              value: "443"
            - name: GHOST_SKIP_BOOTSTRAP
              value: "no"
          ports:
            - name: http
              containerPort: 2368
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: "http"
              scheme: "HTTP"
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: "http"
              scheme: "HTTP"
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6
            successThreshold: 1
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: ghost-data
              mountPath: /bitnami/ghost
      volumes:
        - name: ghost-data
          persistentVolumeClaim:
            claimName: demo-ghost
