apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: demo-ghost
  namespace: ghost
spec:
  encryptedData:
    ghost-password: AgAqKtx4WOzjJ1GFNlxHljUI+C/nez2tzA1UEPBIa/pOgeUKrcRzCMwSoa9GeQdEqzRv5Kheharmi2E+L0RBOqV+J80tls4fBWZzj3FxJzV+2cED1RtHsvYi4MbImXLPDW5M55OIvaYuIvO7ueGIvVPiiyQoMFBtrxjFVDD8T6rLuV5IPFmK7chOodzAKLX+hzn8CUtXtynrAZ38dNEnGozIg0mXNTBnlZ5csGg7f3ktn9H0VyC+B6MQDDhCOJlACUbKnGfdlF0itMJVc1m6lE792wAKAVL2aARJM5A7+hyhKjnnnoeZJOuzW0WvTQwluN2rQJ7lA/PtNxKUW4wLOLCAA6D+QjCJ7w0p4355FQRgh1VxoHELzMyw9cDkxE/wv2uP+wYtkWykkkJ1IQRuVLkUoBbPq8DBM5Xuv8fnPjDSq5MfQN+v503BtvsN+ETh0PgLDuTcJI6HtBvPD0PRAhi6O2lfY1T7hP0uh31uE2X0ofnHToUjWHYrvN9o0nx2xBL2USTWZFmluqaCjiFzrogqvH+80qkm8xgobm2fQmLSofU3guSI5UHaNWRVqXrSXMJ06e5P6OkiX+QTpqtqQmm9ALUZ5evzmP6tC3bT7ch17HrWyACx+BscwERf/h1H/wrUOxwFWztLlDv5IwOz4DaHnnY3ntWEe0hQEFu/+/bvVtCNkj/Ixa1rsCjOskHfT/3oFsbB0PBtnAk8
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: demo
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: ghost
        helm.sh/chart: ghost-15.1.0
      name: demo-ghost
      namespace: ghost
    type: Opaque

