---
# Source: ghost/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-release-ghost
  namespace: "ghost"
  labels:
    app.kubernetes.io/name: ghost
    helm.sh/chart: ghost-15.1.0
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  ghostPass: "RU5DW0FFUzI1Nl9HQ00sZGF0YToyR0F3K0ZCN0RwQXJYZz09LGl2OlorYnVySVVJUWExbHJSQVFCSXZOZWczM291eDhKRHR0ZVRETTJQL0lLbG89LHRhZzpHNS8yOVBSZStwZnlXbVd6ZWxrZnVnPT0sdHlwZTpzdHJd"
  mariaPass: "RU5DW0FFUzI1Nl9HQ00sZGF0YTpLVEVoT053dlV0NTlWUT09LGl2OnI4RUloSFlLZjVuTGovMkJsYStUZnBZODdGYjRXMythanQvTUwvamJhbzQ9LHRhZzpoNCtCS2pOUzBGb0dqclBldjl3QWV3PT0sdHlwZTpzdHJd"
  mariaRootPass: "RU5DW0FFUzI1Nl9HQ00sZGF0YTp6Z0J5dTlaZFU1NGI3dz09LGl2OldTT2IxeXZUNkZKeitpcnlmeFFxUy9NSlJMM21jN3BuZUtVSzA2T2FuRGs9LHRhZzpER1lraTc5clVZaE5jMTBDclp3WjdnPT0sdHlwZTpzdHJd"
