---
# Source: ghost/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-ghost
  namespace: "ghost"
  labels:
    app.kubernetes.io/name: ghost
    helm.sh/chart: ghost-15.1.0
    app.kubernetes.io/instance: my-ghost
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: ghost
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Cluster"
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/instance: my-ghost
    app.kubernetes.io/component: ghost
