---
# Source: ghost/charts/mariadb/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-ghost-mariadb
  namespace: ghost
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-9.8.1
    app.kubernetes.io/instance: my-ghost
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
      nodePort: null
  selector: 
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: my-ghost
    app.kubernetes.io/component: primary
