---
# Source: ghost/charts/mariadb/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: demo-mariadb
  namespace: ghost
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-9.8.1
    app.kubernetes.io/instance: demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
  annotations:
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Cluster"
  sessionAffinity: None
  ports:
    - name: mysql
      port: 8080
      targetPort: 3306
  selector: 
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: demo
    app.kubernetes.io/component: primary
