apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: ghost
type: Opaque
data:
  ghost-password: "ZkpHWVk4RGI4OQ=="
  mariadb-root-password: "a1R4TEVYNEhLMA=="
  mariadb-password: "RzZqSlpvOWUzVA=="