---
# Source: ghost/charts/mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: demo-mariadb
  namespace: ghost
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-9.8.1
    app.kubernetes.io/instance: demo
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mariadb-root-password: "N2V3OXgwc2lWaA=="
  mariadb-password: "UG5OcUt0dFdCaA=="
