---
# Source: ghost/charts/mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-ghost-mariadb
  namespace: ghost
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-9.8.1
    app.kubernetes.io/instance: my-ghost
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mariadb-root-password: "R2dmZ1ZCVkNrWg=="
  mariadb-password: "Uk5mOFVDa2VSNA=="
