---
# Source: ghost/charts/mariadb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-mariadb
  namespace: ghost
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-9.8.1
    app.kubernetes.io/instance: demo
    app.kubernetes.io/managed-by: Helm
  annotations:
